server:
  port: 8080
 
spring:
  datasource:
    url: jdbc:mysql://localhost/library_db
    username: root
    password: Kristina@14
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: BOOKCATALOG-SERVICE
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}